#!/usr/bin/env zsh

cargo install --path .

harness=${HOME}/Dropbox/projects/craftinginterpreters/tool/bin/test.dart
interpreter=chap13_inheritance
my_lox=rlox

dart $harness $interpreter --interpreter $my_lox
