#!/usr/bin/env zsh

cargo install --path .

harness=/Users/jackson/Dropbox/projects/craftinginterpreters/tool/bin/test.dart
interpreter=chap13_inheritance
my_lox=/Users/jackson/.cargo/bin/rlox

dart $harness $interpreter --interpreter $my_lox
